### ISSUE TITLE
PoC YAML scenario parser

### ISSUE THREAD

**Issue by markaren** [open-simulation-platform/libcosim#271]
If there are no objections I want to add a proof of concept scenario parser that uses YAML instead of JSON. YAML is easier to write, looks better and supports comments. 

Compare

```json
{
  "defaults": {
    "model": "slave uno",
    "variable": "realOut",
    "causality": "input",
    "type": "integer",
    "action": "override"
  },
  "events": [
    {
      "time": 0.5,
      "variable": "realIn",
      "type": "real",
      "action": "bias",
      "value": 1.001
    },
    {
      "time": 0.2,
      "causality": "output",
      "type": "real",
      "value": -1.0
    },
    {
      "time": 0.3,
      "causality": "output",
      "type": "real",
      "action": "reset"
    },
    {
      "time": 0.65,
      "variable": "intIn",
      "value": 2
    },
    {
      "time": 0.8,
      "variable": "intOut",
      "causality": "output",
      "value": 5
    }
  ],
  "end": 1.0
}
```

to

```yaml
---
defaults:
  model: slave uno
  variable: realOut
  causality: input
  type: integer
  action: override
events:
- time: 0.5
  variable: realIn
  type: real
  action: bias
  value: 1.001
- time: 0.2
  causality: output
  type: real
  value: -1
- time: 0.3
  causality: output
  type: real
  action: reset
- time: 0.65
  variable: intIn
  value: 2
- time: 0.8
  variable: intOut
  causality: output
  value: 5
end: 1

```

Since `scenario_parser.hpp` is implementation agnostic, we could potentially support both. But we should probably decide on a final format at some point. 

C++ YAML parser is available from: conan: https://github.com/bincrafters/conan-yaml-cpp 

No timeline given. Don't know when I'll have time.
